# Generated by Django 4.0.4 on 2022-05-17 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ends_on', models.DateField()),
                ('custom_user', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DATERECORDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.IntegerField()),
                ('habit', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
            ],
        ),
    ]
