# Generated by Django 4.0.4 on 2022-05-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daterecord',
            options={},
        ),
    ]
