# Generated by Django 4.0.4 on 2022-05-17 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_daterecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DATERECORDS',
            new_name='DATERECORD',
        ),
        migrations.AlterField(
            model_name='habit',
            name='custom_user',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
    ]
