# Generated by Django 4.0.4 on 2022-05-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_rename_daterecords_daterecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterecord',
            name='habit',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='daterecords', to='habit.habit'),
        ),
    ]
